
USE master
GO

USE HeroDB



DROP TABLE IF EXISTS VILLAIN
DROP TABLE IF EXISTS HERO
DROP TABLE IF EXISTS GAME

CREATE TABLE GAME(
    GameId INT Primary KEY,
    Winner NVARCHAR(1)
    CHECK(Winner IN ('W','L')),
    [DateTime] Date
)

CREATE TABLE HERO(
    heroId NVARCHAR(10) PRIMARY KEY,
    CharacterName NVARCHAR(100),
    MAXDAMAGE INT NOT NULL, 
    MINDAMAGE INT NOT NULL
)

CREATE TABLE VILLAIN(
    VillainId NVARCHAR(10) PRIMARY KEY,
    VillanName NVARCHAR(100),
    VHealth INT
)

INSERT INTO Hero VALUES(1,'Hero1',6,1)
INSERT INTO Hero VALUES (2,'Hero2', 10,4)

INSERT INTO Villain VALUES(1,'Villain1',1)
INSERT INTO Villain VALUES(2,'Villain2',1)
INSERT INTO Villain VALUES(3,'Villain3',1)
INSERT INTO Villain VALUES(4,'Villain4',1)

INSERT INTO GAME VALUES(1,'W','1-11-2021')
INSERT INTO GAME VALUES(2,'W','1-11-2020')


Select * From Villain
SELECT * FROM Hero
SELECT * FROM GAME
